name: SOOS DAST GitHub Action

# Controls when the workflow will run
on: [push]

jobs:
  soos_dast_analysis_example:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis Test
        uses: soos-io/soos-dast-github-action@feature/PA-5101
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: ${{ github.repository }}
          scan_mode: 'baseline'
          api_url: "https://qa-api.soos.io/api/"
          target_url: "https://brokencrystals.com/"
          output_format: "sarif"
      - name: Upload SOOS DAST Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
